version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container-warrini
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - ./postgres-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
