spring:
  application:
    name: warrini
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  logging:
    level:
      org:
        springframework:
          web: DEBUG
          security: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: spring
      password: spring