server:
  port: ${PORT:8080}  # Uses PORT environment variable or defaults to 8080 if not set

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:warrini}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}


  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: spring
      password: spring