spring:
  application:
    name: warrini
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: spring
      password: spring